openapi: "3.0.1"
info:
  title: "micro-blogger"
  version: "1.0"
paths:
  /message:
    post:
      responses:
        "200":
          description: "OK"
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${SQSIntegrationRole.Arn}
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:sqs:path/${AWS::AccountId}/${BlogCommandQueue.QueueName}"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "Action=SendMessage&MessageBody=$input.body"
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        passthroughBehavior: "when_no_match"
        type: "aws"
  /message/{message_id}:
    get:
      summary: Get message by id
      description: Returns a single message per id
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMessageFunction.Arn}/invocations
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

components: {}
